### ISSUE TITLE
Can’t organize sections on top

### ISSUE THREAD

**Issue by rafaelmafra** [johnzaro/PerfectSettings13#1]
I have an iPhone X on 13.5 and installed PerfectSettings13, then check the first option to make tweaks, apps and system apps to stay on top of settings. However they still down to the stock position.

Thanks in advance.
![8EFBF99E-B7F8-4358-9A48-847936BE5A27](https://user-images.githubusercontent.com/7586296/83304487-538bd380-a1d5-11ea-80f2-50919b91f827.png)
![4394B50A-EBD9-4409-98F2-233FEC933089](https://user-images.githubusercontent.com/7586296/83304496-5686c400-a1d5-11ea-94fc-4287e9741629.png)

**Comment by johnzaro** [comment]
I am aware if that issue. It happens on some devices only. I am already
trying to find a fix

**Comment by rafaelmafra** [comment]
All right. Keep going your good work. If you need some help as a tester or something, feel free to contact me.

**Comment by fr0stf0x** [comment]
Same here on my device. Everything else works nicely
